# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page-start.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(1280, 800)
        LoginDialog.setStyleSheet("QDialog {\n"
"    background-color: #1a1a1a;\n"
"}\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #3d3d3d;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    background: #2d2d2d;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    min-height: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50;\n"
"}\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #4CAF50;\n"
"    color: #4CAF50;\n"
"    padding: 12px 24px;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-height: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}\n"
"QPushButton#registerButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #4CAF50;\n"
"    color: #4CAF50;\n"
"}\n"
"QPushButton#registerButton:hover {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}\n"
"QLabel {\n"
"    color: #ffffff;\n"
"}\n"
"QLabel#logoLabel {\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #4CAF50;\n"
"}\n"
"QLabel#welcomeLabel {\n"
"    font-size: 18px;\n"
"    color: #ffffff;\n"
"}\n"
"QLabel#descriptionLabel {\n"
"    font-size: 16px;\n"
"    color: #b0b0b0;\n"
"}\n"
"QLabel#switchLabel {\n"
"    color: #4CAF50;\n"
"    font-size: 14px;\n"
"    padding: 12px 24px;\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 8px;\n"
"    background-color: transparent;\n"
"    margin: 10px 0;\n"
"    transition: all 0.3s ease;\n"
"}\n"
"QLabel#switchLabel:hover {\n"
"    color: white;\n"
"    background-color: #4CAF50;\n"
"    cursor: pointer;\n"
"    transform: translateY(-2px);\n"
"    box-shadow: 0 4px 8px rgba(76, 175, 80, 0.2);\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    spacing: 8px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4CAF50;\n"
"    border-color: #4CAF50;\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #45a049;\n"
"}\n"
"QLabel#forgotPasswordLink {\n"
"    color: #4CAF50;\n"
"    font-size: 14px;\n"
"    text-decoration: underline;\n"
"    cursor: pointer;\n"
"    margin: 5px 0;\n"
"}\n"
"QLabel#forgotPasswordLink:hover {\n"
"    color: #45a049;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanel = QtWidgets.QWidget(LoginDialog)
        self.leftPanel.setStyleSheet("background-color: #2d2d2d;")
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.logoLabel = QtWidgets.QLabel(self.leftPanel)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel)
        self.welcomeLabel = QtWidgets.QLabel(self.leftPanel)
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.verticalLayout.addWidget(self.welcomeLabel)
        self.descriptionLabel = QtWidgets.QLabel(self.leftPanel)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.leftPanel)
        self.rightPanel = QtWidgets.QWidget(LoginDialog)
        self.rightPanel.setStyleSheet("background-color: #1a1a1a;")
        self.rightPanel.setObjectName("rightPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightPanel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.rightPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loginPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginTitle = QtWidgets.QLabel(self.loginPage)
        self.loginTitle.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #ffffff;")
        self.loginTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.loginTitle.setObjectName("loginTitle")
        self.verticalLayout_3.addWidget(self.loginTitle)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.usernameInput = QtWidgets.QLineEdit(self.loginPage)
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout_3.addWidget(self.usernameInput)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.passwordInput = QtWidgets.QLineEdit(self.loginPage)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout_3.addWidget(self.passwordInput)
        self.forgotPasswordLink = QtWidgets.QLabel(self.loginPage)
        self.forgotPasswordLink.setStyleSheet("color: #4CAF50;\n"
"font-size: 14px;\n"
"text-decoration: underline;\n"
"cursor: pointer;\n"
"margin: 5px 0;")
        self.forgotPasswordLink.setAlignment(QtCore.Qt.AlignRight)
        self.forgotPasswordLink.setObjectName("forgotPasswordLink")
        self.verticalLayout_3.addWidget(self.forgotPasswordLink)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.loginButton = QtWidgets.QPushButton(self.loginPage)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_3.addWidget(self.loginButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.switchToRegister = QtWidgets.QLabel(self.loginPage)
        self.switchToRegister.setStyleSheet("color: #4CAF50;\n"
"font-size: 14px;\n"
"padding: 12px 24px;\n"
"border: 2px solid #4CAF50;\n"
"border-radius: 8px;\n"
"background-color: transparent;\n"
"margin: 10px 0;\n"
"transition: all 0.3s ease;")
        self.switchToRegister.setAlignment(QtCore.Qt.AlignCenter)
        self.switchToRegister.setObjectName("switchToRegister")
        self.verticalLayout_3.addWidget(self.switchToRegister)
        self.stackedWidget.addWidget(self.loginPage)
        self.registerPage = QtWidgets.QWidget()
        self.registerPage.setObjectName("registerPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.registerPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.registerTitle = QtWidgets.QLabel(self.registerPage)
        self.registerTitle.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #ffffff;")
        self.registerTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.registerTitle.setObjectName("registerTitle")
        self.verticalLayout_4.addWidget(self.registerTitle)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.fullNameInput = QtWidgets.QLineEdit(self.registerPage)
        self.fullNameInput.setObjectName("fullNameInput")
        self.verticalLayout_4.addWidget(self.fullNameInput)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.registerUsernameInput = QtWidgets.QLineEdit(self.registerPage)
        self.registerUsernameInput.setObjectName("registerUsernameInput")
        self.verticalLayout_4.addWidget(self.registerUsernameInput)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.emailInput = QtWidgets.QLineEdit(self.registerPage)
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout_4.addWidget(self.emailInput)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.registerPasswordInput = QtWidgets.QLineEdit(self.registerPage)
        self.registerPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerPasswordInput.setObjectName("registerPasswordInput")
        self.verticalLayout_4.addWidget(self.registerPasswordInput)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.confirmPasswordInput = QtWidgets.QLineEdit(self.registerPage)
        self.confirmPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordInput.setObjectName("confirmPasswordInput")
        self.verticalLayout_4.addWidget(self.confirmPasswordInput)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.privacyCheckbox = QtWidgets.QCheckBox(self.registerPage)
        self.privacyCheckbox.setObjectName("privacyCheckbox")
        self.verticalLayout_4.addWidget(self.privacyCheckbox)
        self.privacyLink = QtWidgets.QLabel(self.registerPage)
        self.privacyLink.setStyleSheet("color: #4CAF50;\n"
"font-size: 14px;\n"
"text-decoration: underline;")
        self.privacyLink.setAlignment(QtCore.Qt.AlignCenter)
        self.privacyLink.setObjectName("privacyLink")
        self.verticalLayout_4.addWidget(self.privacyLink)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.registerButton = QtWidgets.QPushButton(self.registerPage)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout_4.addWidget(self.registerButton)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.switchToLogin = QtWidgets.QLabel(self.registerPage)
        self.switchToLogin.setStyleSheet("color: #4CAF50;\n"
"font-size: 14px;\n"
"padding: 12px 24px;\n"
"border: 2px solid #4CAF50;\n"
"border-radius: 8px;\n"
"background-color: transparent;\n"
"margin: 10px 0;\n"
"transition: all 0.3s ease;")
        self.switchToLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.switchToLogin.setObjectName("switchToLogin")
        self.verticalLayout_4.addWidget(self.switchToLogin)
        self.stackedWidget.addWidget(self.registerPage)
        self.privacyPage = QtWidgets.QWidget()
        self.privacyPage.setObjectName("privacyPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.privacyPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.privacyTitle = QtWidgets.QLabel(self.privacyPage)
        self.privacyTitle.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #ffffff;")
        self.privacyTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.privacyTitle.setObjectName("privacyTitle")
        self.verticalLayout_5.addWidget(self.privacyTitle)
        self.privacyText = QtWidgets.QTextEdit(self.privacyPage)
        self.privacyText.setStyleSheet("background-color: #2d2d2d;\n"
"color: #ffffff;\n"
"border: 1px solid #3d3d3d;\n"
"border-radius: 8px;\n"
"padding: 12px;\n"
"font-size: 14px;")
        self.privacyText.setReadOnly(True)
        self.privacyText.setObjectName("privacyText")
        self.verticalLayout_5.addWidget(self.privacyText)
        self.backToRegisterButton = QtWidgets.QPushButton(self.privacyPage)
        self.backToRegisterButton.setObjectName("backToRegisterButton")
        self.verticalLayout_5.addWidget(self.backToRegisterButton)
        self.stackedWidget.addWidget(self.privacyPage)
        self.forgotPasswordPage = QtWidgets.QWidget()
        self.forgotPasswordPage.setObjectName("forgotPasswordPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.forgotPasswordPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.forgotPasswordTitle = QtWidgets.QLabel(self.forgotPasswordPage)
        self.forgotPasswordTitle.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #ffffff;")
        self.forgotPasswordTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotPasswordTitle.setObjectName("forgotPasswordTitle")
        self.verticalLayout_6.addWidget(self.forgotPasswordTitle)
        self.forgotPasswordDescription = QtWidgets.QLabel(self.forgotPasswordPage)
        self.forgotPasswordDescription.setStyleSheet("color: #b0b0b0;\n"
"font-size: 14px;\n"
"text-align: center;")
        self.forgotPasswordDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotPasswordDescription.setObjectName("forgotPasswordDescription")
        self.verticalLayout_6.addWidget(self.forgotPasswordDescription)
        self.forgotPasswordEmailInput = QtWidgets.QLineEdit(self.forgotPasswordPage)
        self.forgotPasswordEmailInput.setObjectName("forgotPasswordEmailInput")
        self.verticalLayout_6.addWidget(self.forgotPasswordEmailInput)
        self.sendResetLinkButton = QtWidgets.QPushButton(self.forgotPasswordPage)
        self.sendResetLinkButton.setObjectName("sendResetLinkButton")
        self.verticalLayout_6.addWidget(self.sendResetLinkButton)
        self.backToLoginLink = QtWidgets.QLabel(self.forgotPasswordPage)
        self.backToLoginLink.setStyleSheet("color: #4CAF50;\n"
"font-size: 14px;\n"
"text-decoration: underline;\n"
"cursor: pointer;\n"
"margin: 5px 0;")
        self.backToLoginLink.setAlignment(QtCore.Qt.AlignCenter)
        self.backToLoginLink.setObjectName("backToLoginLink")
        self.verticalLayout_6.addWidget(self.backToLoginLink)
        self.stackedWidget.addWidget(self.forgotPasswordPage)
        self.emailVerificationPage = QtWidgets.QWidget()
        self.emailVerificationPage.setObjectName("emailVerificationPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.emailVerificationPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verificationTitle = QtWidgets.QLabel(self.emailVerificationPage)
        self.verificationTitle.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #ffffff;")
        self.verificationTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.verificationTitle.setObjectName("verificationTitle")
        self.verticalLayout_7.addWidget(self.verificationTitle)
        self.verificationDescription = QtWidgets.QLabel(self.emailVerificationPage)
        self.verificationDescription.setStyleSheet("color: #b0b0b0;\n"
"font-size: 14px;\n"
"text-align: center;")
        self.verificationDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.verificationDescription.setObjectName("verificationDescription")
        self.verticalLayout_7.addWidget(self.verificationDescription)
        self.verificationCodeInput = QtWidgets.QLineEdit(self.emailVerificationPage)
        self.verificationCodeInput.setMaxLength(6)
        self.verificationCodeInput.setObjectName("verificationCodeInput")
        self.verticalLayout_7.addWidget(self.verificationCodeInput)
        self.verifyCodeButton = QtWidgets.QPushButton(self.emailVerificationPage)
        self.verifyCodeButton.setObjectName("verifyCodeButton")
        self.verticalLayout_7.addWidget(self.verifyCodeButton)
        self.resendCodeLink = QtWidgets.QLabel(self.emailVerificationPage)
        self.resendCodeLink.setStyleSheet("color: #4CAF50;\n"
"font-size: 14px;\n"
"text-decoration: underline;\n"
"cursor: pointer;\n"
"margin: 5px 0;")
        self.resendCodeLink.setAlignment(QtCore.Qt.AlignCenter)
        self.resendCodeLink.setObjectName("resendCodeLink")
        self.verticalLayout_7.addWidget(self.resendCodeLink)
        self.stackedWidget.addWidget(self.emailVerificationPage)
        self.resetPasswordPage = QtWidgets.QWidget()
        self.resetPasswordPage.setObjectName("resetPasswordPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.resetPasswordPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.resetPasswordTitle = QtWidgets.QLabel(self.resetPasswordPage)
        self.resetPasswordTitle.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #ffffff;")
        self.resetPasswordTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.resetPasswordTitle.setObjectName("resetPasswordTitle")
        self.verticalLayout_8.addWidget(self.resetPasswordTitle)
        self.resetPasswordDescription = QtWidgets.QLabel(self.resetPasswordPage)
        self.resetPasswordDescription.setStyleSheet("color: #b0b0b0;\n"
"font-size: 14px;\n"
"text-align: center;")
        self.resetPasswordDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.resetPasswordDescription.setObjectName("resetPasswordDescription")
        self.verticalLayout_8.addWidget(self.resetPasswordDescription)
        self.resetCodeInput = QtWidgets.QLineEdit(self.resetPasswordPage)
        self.resetCodeInput.setMaxLength(6)
        self.resetCodeInput.setObjectName("resetCodeInput")
        self.verticalLayout_8.addWidget(self.resetCodeInput)
        self.verifyResetCodeButton = QtWidgets.QPushButton(self.resetPasswordPage)
        self.verifyResetCodeButton.setObjectName("verifyResetCodeButton")
        self.verticalLayout_8.addWidget(self.verifyResetCodeButton)
        self.resendResetCodeLink = QtWidgets.QLabel(self.resetPasswordPage)
        self.resendResetCodeLink.setStyleSheet("color: #4CAF50;\n"
"font-size: 14px;\n"
"text-decoration: underline;\n"
"cursor: pointer;\n"
"margin: 5px 0;")
        self.resendResetCodeLink.setAlignment(QtCore.Qt.AlignCenter)
        self.resendResetCodeLink.setObjectName("resendResetCodeLink")
        self.verticalLayout_8.addWidget(self.resendResetCodeLink)
        self.stackedWidget.addWidget(self.resetPasswordPage)
        self.newPasswordPage = QtWidgets.QWidget()
        self.newPasswordPage.setObjectName("newPasswordPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.newPasswordPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.newPasswordTitle = QtWidgets.QLabel(self.newPasswordPage)
        self.newPasswordTitle.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #ffffff;")
        self.newPasswordTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.newPasswordTitle.setObjectName("newPasswordTitle")
        self.verticalLayout_9.addWidget(self.newPasswordTitle)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem15)
        self.newPasswordDescription = QtWidgets.QLabel(self.newPasswordPage)
        self.newPasswordDescription.setStyleSheet("color: #b0b0b0;\n"
"font-size: 14px;\n"
"text-align: center;")
        self.newPasswordDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.newPasswordDescription.setObjectName("newPasswordDescription")
        self.verticalLayout_9.addWidget(self.newPasswordDescription)
        self.newPasswordInput = QtWidgets.QLineEdit(self.newPasswordPage)
        self.newPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordInput.setObjectName("newPasswordInput")
        self.verticalLayout_9.addWidget(self.newPasswordInput)
        self.confirmNewPasswordInput = QtWidgets.QLineEdit(self.newPasswordPage)
        self.confirmNewPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmNewPasswordInput.setObjectName("confirmNewPasswordInput")
        self.verticalLayout_9.addWidget(self.confirmNewPasswordInput)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem16)
        self.saveNewPasswordButton = QtWidgets.QPushButton(self.newPasswordPage)
        self.saveNewPasswordButton.setObjectName("saveNewPasswordButton")
        self.verticalLayout_9.addWidget(self.saveNewPasswordButton)
        self.stackedWidget.addWidget(self.newPasswordPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        spacerItem17 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.horizontalLayout.addWidget(self.rightPanel)

        self.retranslateUi(LoginDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "SosyalPiyon - Giriş"))    
        self.logoLabel.setText(_translate("LoginDialog", "SosyalPiyon"))
        self.welcomeLabel.setText(_translate("LoginDialog", "Satranç Dünyasına Hoş Geldiniz"))
        self.descriptionLabel.setText(_translate("LoginDialog", "Satranç tutkunlarıyla buluşun, sohbet edin, stratejilerinizi paylaşın ve yeni arkadaşlar edinin."))
        self.loginTitle.setText(_translate("LoginDialog", "Giriş Yap"))
        self.usernameInput.setPlaceholderText(_translate("LoginDialog", "Kullanıcı adınızı girin"))
        self.passwordInput.setPlaceholderText(_translate("LoginDialog", "Şifrenizi girin"))
        self.forgotPasswordLink.setText(_translate("LoginDialog", "Şifremi Unuttum"))
        self.loginButton.setText(_translate("LoginDialog", "Giriş Yap"))
        self.switchToRegister.setText(_translate("LoginDialog", "Hesabınız yok mu? Kayıt olun"))
        self.registerTitle.setText(_translate("LoginDialog", "Kayıt Ol"))
        self.fullNameInput.setPlaceholderText(_translate("LoginDialog", "Adınız ve soyadınız"))
        self.registerUsernameInput.setPlaceholderText(_translate("LoginDialog", "Kullanıcı adı"))
        self.emailInput.setPlaceholderText(_translate("LoginDialog", "E-posta adresiniz"))
        self.registerPasswordInput.setPlaceholderText(_translate("LoginDialog", "Şifre"))
        self.confirmPasswordInput.setPlaceholderText(_translate("LoginDialog", "Şifrenizi tekrar girin"))
        self.privacyCheckbox.setText(_translate("LoginDialog", "Gizlilik sözleşmesini okudum ve kabul ediyorum"))
        self.privacyLink.setText(_translate("LoginDialog", "Gizlilik sözleşmesini oku"))
        self.registerButton.setText(_translate("LoginDialog", "Kayıt Ol"))
        self.switchToLogin.setText(_translate("LoginDialog", "Zaten hesabınız var mı? Giriş yapın"))
        self.privacyTitle.setText(_translate("LoginDialog", "Gizlilik Sözleşmesi"))
        self.privacyText.setText(_translate("LoginDialog", "SOSYALPİYON GİZLİLİK SÖZLEŞMESİ\n\n"
"1. Kişisel Verilerin Korunması\n"
"- Kullanıcı bilgileriniz güvenli bir şekilde saklanır ve şifrelenir\n"
"- Üçüncü taraflarla paylaşılmaz\n"
"- KVKK kapsamında korunur\n"
"- Verileriniz sadece hizmet kalitesini artırmak için kullanılır\n\n"
"2. Veri Kullanımı\n"
"- Hesap yönetimi ve kimlik doğrulama için kullanılır\n"
"- Hizmet kalitesini artırmak için analiz edilir\n"
"- Spam ve kötüye kullanımı önlemek için kullanılır\n"
"- Satranç oyun istatistiklerinizi kaydetmek için kullanılır\n\n"
"3. Çerezler ve Oturum Yönetimi\n"
"- Oturum yönetimi için kullanılır\n"
"- Kullanıcı tercihlerini hatırlamak için kullanılır\n"
"- Güvenlik için kullanılır\n"
"- Satranç oyun ayarlarınızı saklamak için kullanılır\n\n"
"4. Güvenlik Önlemleri\n"
"- SSL şifreleme kullanılır\n"
"- Düzenli güvenlik güncellemeleri yapılır\n"
"- Veri yedekleme sistemleri mevcuttur\n"
"- İki faktörlü kimlik doğrulama seçeneği sunulur\n\n"
"5. Kullanıcı Hakları\n"
"- Verilerinize erişim hakkı\n"
"- Verilerinizin düzeltilmesini talep etme hakkı\n"
"- Verilerinizin silinmesini talep etme hakkı\n"
"- Veri işlemeye itiraz etme hakkı\n\n"
"6. İletişim\n"
"Gizlilik politikamız hakkında sorularınız için:\n"
"E-posta: bariscanceken@hotmail.com\n"
"Telefon: +90 (530) 579 29 36"))
        self.backToRegisterButton.setText(_translate("LoginDialog", "Geri Dön"))
        self.forgotPasswordTitle.setText(_translate("LoginDialog", "Şifremi Unuttum"))
        self.forgotPasswordDescription.setText(_translate("LoginDialog", "E-posta adresinizi girin, size şifre sıfırlama bağlantısı gönderelim."))
        self.forgotPasswordEmailInput.setPlaceholderText(_translate("LoginDialog", "E-posta adresiniz"))
        self.sendResetLinkButton.setText(_translate("LoginDialog", "Şifre Sıfırlama Bağlantısı Gönder"))
        self.backToLoginLink.setText(_translate("LoginDialog", "Giriş sayfasına dön"))
        self.verificationTitle.setText(_translate("LoginDialog", "E-posta Doğrulama"))
        self.verificationDescription.setText(_translate("LoginDialog", "E-posta adresinize gönderilen 6 haneli doğrulama kodunu girin."))
        self.verificationCodeInput.setPlaceholderText(_translate("LoginDialog", "Doğrulama kodu"))
        self.verifyCodeButton.setText(_translate("LoginDialog", "Doğrula"))
        self.resendCodeLink.setText(_translate("LoginDialog", "Kodu tekrar gönder"))
        self.resetPasswordTitle.setText(_translate("LoginDialog", "Şifre Sıfırlama"))
        self.resetPasswordDescription.setText(_translate("LoginDialog", "E-posta adresinize gönderilen 6 haneli doğrulama kodunu girin."))
        self.resetCodeInput.setPlaceholderText(_translate("LoginDialog", "Doğrulama kodu"))
        self.verifyResetCodeButton.setText(_translate("LoginDialog", "Kodu Doğrula"))
        self.resendResetCodeLink.setText(_translate("LoginDialog", "Kodu tekrar gönder"))
        self.newPasswordTitle.setText(_translate("LoginDialog", "Yeni Şifre Belirleme"))
        self.newPasswordDescription.setText(_translate("LoginDialog", "Lütfen yeni şifrenizi belirleyin."))
        self.newPasswordInput.setPlaceholderText(_translate("LoginDialog", "Yeni şifre"))
        self.confirmNewPasswordInput.setPlaceholderText(_translate("LoginDialog", "Yeni şifrenizi tekrar girin"))
        self.saveNewPasswordButton.setText(_translate("LoginDialog", "Şifreyi Kaydet"))


class LoginDialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_LoginDialog()
        self.ui.setupUi(self)
        
        # Tıklama olaylarını bağla
        self.ui.loginButton.clicked.connect(self.handle_login)
        self.ui.registerButton.clicked.connect(self.handle_register)
        self.ui.switchToRegister.mousePressEvent = self.switch_to_register
        self.ui.switchToLogin.mousePressEvent = self.switch_to_login
        self.ui.forgotPasswordLink.mousePressEvent = self.show_forgot_password
        self.ui.privacyLink.mousePressEvent = self.show_privacy
        self.ui.backToRegisterButton.clicked.connect(self.switch_to_register)
        self.ui.backToLoginLink.mousePressEvent = self.switch_to_login
        self.ui.sendResetLinkButton.clicked.connect(self.handle_send_reset_link)
        self.ui.verifyCodeButton.clicked.connect(self.handle_verify_code)
        self.ui.resendCodeLink.mousePressEvent = self.handle_resend_code
        self.ui.verifyResetCodeButton.clicked.connect(self.handle_verify_reset_code)
        self.ui.resendResetCodeLink.mousePressEvent = self.handle_resend_reset_code
        self.ui.saveNewPasswordButton.clicked.connect(self.handle_save_new_password)

    def handle_login(self):
        username = self.ui.usernameInput.text()
        password = self.ui.passwordInput.text()
        # Giriş işlemleri burada yapılacak
        print(f"Giriş yapılıyor: {username}")

    def handle_register(self):
        if not self.ui.privacyCheckbox.isChecked():
            QtWidgets.QMessageBox.warning(self, "Uyarı", "Lütfen gizlilik sözleşmesini kabul edin.")
            return
            
        full_name = self.ui.fullNameInput.text()
        username = self.ui.registerUsernameInput.text()
        email = self.ui.emailInput.text()
        password = self.ui.registerPasswordInput.text()
        confirm_password = self.ui.confirmPasswordInput.text()
        
        if password != confirm_password:
            QtWidgets.QMessageBox.warning(self, "Uyarı", "Şifreler eşleşmiyor!")
            return
            
        # Kayıt işlemleri burada yapılacak
        print(f"Kayıt yapılıyor: {username}")

    def switch_to_register(self, event=None):
        self.ui.stackedWidget.setCurrentWidget(self.ui.registerPage)

    def switch_to_login(self, event=None):
        self.ui.stackedWidget.setCurrentWidget(self.ui.loginPage)

    def show_forgot_password(self, event):
        self.ui.stackedWidget.setCurrentWidget(self.ui.forgotPasswordPage)

    def show_privacy(self, event):
        self.ui.stackedWidget.setCurrentWidget(self.ui.privacyPage)

    def handle_send_reset_link(self):
        email = self.ui.forgotPasswordEmailInput.text()
        # Şifre sıfırlama bağlantısı gönderme işlemleri burada yapılacak
        print(f"Şifre sıfırlama bağlantısı gönderiliyor: {email}")

    def handle_verify_code(self):
        code = self.ui.verificationCodeInput.text()
        # Doğrulama kodu kontrolü burada yapılacak
        print(f"Doğrulama kodu kontrol ediliyor: {code}")

    def handle_resend_code(self, event):
        # Yeni doğrulama kodu gönderme işlemleri burada yapılacak
        print("Yeni doğrulama kodu gönderiliyor")

    def handle_verify_reset_code(self):
        code = self.ui.resetCodeInput.text()
        # Şifre sıfırlama kodu kontrolü burada yapılacak
        print(f"Şifre sıfırlama kodu kontrol ediliyor: {code}")

    def handle_resend_reset_code(self, event):
        # Yeni şifre sıfırlama kodu gönderme işlemleri burada yapılacak
        print("Yeni şifre sıfırlama kodu gönderiliyor")

    def handle_save_new_password(self):
        new_password = self.ui.newPasswordInput.text()
        confirm_password = self.ui.confirmNewPasswordInput.text()
        
        if new_password != confirm_password:
            QtWidgets.QMessageBox.warning(self, "Uyarı", "Şifreler eşleşmiyor!")
            return
            
        # Yeni şifre kaydetme işlemleri burada yapılacak
        print("Yeni şifre kaydediliyor")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = LoginDialog()
    window.show()
    sys.exit(app.exec_())
